'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

fib = [1,1]
while fib[-1]<4000000:
    fib.append(fib[-2]+fib[-1])
fib.remove(fib[-1])
#we now have a list of all fibonnaci terms.
#note that the sequence is odd-odd-even. Every third term is even.
#therefore we merely slice out every third term to get the even ones.
print(str(sum(fib[2::3])))
